#!/bin/bash

{ # Prevent script running if partially downloaded

set -euo pipefail

# Lifted from https://github.com/kalbasit/shabka/blob/8f6ba74a9670cc3aad384abb53698f9d4cea9233/os-specific/darwin/setup.sh#L22
sudo_prompt() {
  echo "Please enter your password for sudo authentication"
  sudo -k
  sudo echo "sudo authenticaion successful!"
  while true ; do sudo -n true ; sleep 60 ; kill -0 "$$" || exit ; done 2>/dev/null &
}

install_command_line_tools() {
  # Unattended installation of Command Line Tools
  # Found on apple.stackexchange.com at https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line/195963#195963
  # Homebrew uses a similar technique https://github.com/Homebrew/install/blob/878b5a18b89ff73f2f221392ecaabd03c1e69c3f/install#L297
  xcode-select -p >/dev/null || {
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    CLT=$( softwareupdate -l |
      grep "\*.*Command Line Tools" |
      head -n 1 |
      awk -F ":" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n' )
    softwareupdate -i "$CLT" --verbose
    rm /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
  }
  echo "Command Line Tools are installed at $(xcode-select -p)"
}

install_nix() {
  command -v nix >/dev/null || {
    # printf responses based on:
    #    - Would you like to see a more detailed list of what we will do? n
    #    - Can we use sudo? y
    #    - Ready to continue? y
    printf "n\ny\ny" | sh <(curl -fsSL https://nixos.org/nix/install) --daemon --darwin-use-unencrypted-nix-store-volume
    # Update local shell 
    source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
  }
  nix-shell -p nix-info --run "nix-info -m"
}

install_nix_darwin() {
  command -v darwin-rebuild >/dev/null || {
    nix-build https://github.com/LnL7/nix-darwin/archive/master.tar.gz -A installer

    # nix-darwin controls nix.conf
    sudo mv /etc/nix/nix.conf /etc/nix/nix.conf.backup-before-nix-darwin --out-link /tmp/nix-darwin

    # printf based on:
    #   - Would you like to edit the configuration.nix before starting? n
    #   - Would you like to manage <darwin> with nix-channel? y
    #   - Would you like to load Darwin configuration in /etc/bashrc? y
    #   - Would you like to load Darwin configuration in /etc/zshrc? y
    #   - Would you like to create /run? y
    printf "n\ny\ny\ny\ny" | /tmp/nix-darwin/bin/darwin-installer
  }
}

install_homebrew() {
  command -v brew || {
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  }
  brew doctor
}

clone_repository() {
  clone_target="${HOME}/.nixpkgs"
  rm -rf "${clone_target}"
  git clone https://github.com/TheOptimist/systemosaurus.git "${clone_target}"
}

darwin_build() {
  for filename in shells bashrc zshrc; do
    filepath="/etc/${filename}"
    if [ -f "${filepath}" ] && [ ! -L "${filepath}" ]; then
      sudo mv "${filepath}" "${filepath}.backup-before-nix-darwin"
    fi
  done

  set +u    # Unbound INSIDE_EMACS variable in /etc/bash_Apple_Terminal
  source /etc/static/bashrc
  set -u
  export NIX_PATH=$HOME/.nix-defexpr/channels:$NIX_PATH
  darwin-rebuild switch -I "darwin-config=$HOME/.nixpkgs/darwin/configuration.nix"
}

# Run the installation workflow
sudo_prompt
install_command_line_tools
install_nix
install_nix_darwin
install_homebrew
clone_repository
darwin_build

} # Prevent script running if partially downloaded
